### ISSUE TITLE
'Retreive' is a spelling mistake, should be 'Retrieve'

### ISSUE THREAD

**Issue by rudifa** [facundovictor/jsfiddle-downloader#10]
**Expected:**
<pre>
~ $ jsfiddle-downloader -v -i 5deked8L
Retrieve chunk
. . .
</pre>

**Actual:**
<pre>
~ $ jsfiddle-downloader -v -i 5deked8L
Retreive chunk
. . .
</pre>

**Note:** as I type this comment, even the github spelling checker flags 'retreive' as suspect.
**P.S.** Thank you for this neat utility.

**Comment by facundovictor** [comment]
Hi @rudifa,

Thanks for reporting this. And sorry for the big delay, I didn't have time for checking the issues/PRs.
I see you have a PR that also includes this with a lot of other changes, I'll be testing it manually.
I guess it would be a nice idea to start adding some CI.

Thanks for your collaboration!

**Comment by facundovictor** [comment]
This has been fixed in #12 . Closing.

**Comment by kotenok2000** [comment]
If you replace retreive with retrieve then you should alo replace receive with recieve.
