### ISSUE TITLE
Incompatible with older fiddles

### ISSUE THREAD

**Issue by ghost** [facundovictor/jsfiddle-downloader#25]
using a link, fiddle code and/or version all equally fail:

jsfiddle-downloader -l http://jsfiddle.net/uzMPU/1057
jsfiddle-downloader -l http://jsfiddle.net/uzMPU
jsfiddle-downloader -i uzMPU

Result: an html file the says 404 not found.

Links are working on jsfiddle:
http://jsfiddle.net/uzMPU/1057
http://jsfiddle.net/uzMPU

**Comment by facundovictor** [comment]
All is working with latest version, just tested it with:
```
$ jsfiddle-downloader --version
0.2.1
$ node --version
v10.8.0
```

Please, re-open with:
- Node version used for testing.
- jsfiddle-downloader --version

Thank you!
