### ISSUE TITLE
It downloads a 404 from JSFiddle

### ISSUE THREAD

**Issue by ahrherrera** [facundovictor/jsfiddle-downloader#9]
I tried to download that http://jsfiddle.net/mgmilcher/8R7Xx/sho/

I ran the command `jsfiddle-downloader -l http://jsfiddle.net/mgmilcher/8R7Xx/sho/`

and it downloads the 404

**Comment by facundovictor** [comment]
Yes, I can confirm it in the latest version. It seems that Jsfiddle accepts the url [http://jsfiddle.net/mgmilcher/8R7Xx/sho/](http://jsfiddle.net/mgmilcher/8R7Xx/sho/) like it would be [http://jsfiddle.net/mgmilcher/8R7Xx/](http://jsfiddle.net/mgmilcher/8R7Xx/).
And this tool detects the */sho/* as a version. I'll fix it.

**Comment by facundovictor** [comment]
@ahrherrera, this is fixed. Please do:
`npm install jsfiddle-downloader -g`
And confirm that you've the latest version **(0.1.5)**:
`jsfiddle-downloader --version`
And finally, try again:
`jsfiddle-downloader -l http://jsfiddle.net/mgmilcher/8R7Xx/sho/`

**Comment by facundovictor** [comment]
Please, re-open the issue if you see something wrong with this fix.
